cor-dashboard/config/routes.rb
CorDashboard::Application.routes.draw do
  
  get "patient/", to: "patient#alerts"
  get "patient/metrics"
  get "patient/alerts"
  get "patient/patient_plan"
  get "patient/activity_log"
  get "patient/settings"
  
  get "patient/weight"
  get "patient/blood_oxygen"
  get "patient/heart_rate"
  get "patient/heart_rate_trend"
  get "patient/sodium"
  get "patient/blood_pressure"
  get "patient/medication"
  get "patient/cough"

  get "patient/exercise_log"
  get "patient/sleep_log"
  get "patient/health_summary"
  get "patient/blood_pressure_trend"

  get 'physician/roster'
  get 'physician/critical_patients'
  get 'physician/alerts'
  get 'physician/patients'
  get 'physician/settings'
  get 'physician/summary'
  get 'physician/detail'

  root 'patient#metrics'

  

  

end

cor-dashboard/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CorDashboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

cor-dashboard/app/views/layouts/patient.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cor</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/highcharts-more.js"></script>
	<script src="http://code.highcharts.com/modules/exporting.js"></script>
</head>
<body>
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
	<div class="container-fluid">
		<div class="row">
			<ul class="nav">			
			<li class="col-sm-2 col-sm-offset-1 text-center"><br/><h1>Hello, <%= @patient.name %>!</h1></li>
			<li id="myalerts" class="col-sm-2  text-center"><%= link_to "My Alerts", patient_alerts_path %></li>
			<li id="mymetrics" class="col-sm-2 text-center"><%= link_to "My Metrics", patient_metrics_path, class: "active" %></li>		
			<li id="myactivitylog" class="col-sm-2 text-center"><%= link_to "My Activity Log", patient_activity_log_path %></li>
			<li id="mysettings" class="col-sm-2 text-center"><%= link_to "My Settings", patient_settings_path %></li>

			</ul>
		</div>
		<div class="row bar">
		</div>
	</div>
</div>
<%= yield %>
</body>
</html>

cor-dashboard/app/views/layouts/physician.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ComplexDashboard</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script src="http://code.highcharts.com/highcharts.js"></script>
	<script src="http://code.highcharts.com/modules/exporting.js"></script>
</head>
<body>
<nav class="navbar navbar-default" role="navigation" >
  <div class="container-fluid">
		<div class="navbar-header" style="position: absolute; top: 0px;">
      <h1><%= @physician.name %></h1>
			<%= link_to "Alerts", physician_alerts_path, :class => "btn btn-default btn-lg"%>
			<%= link_to "Patients", physician_roster_path, :class => "btn btn-default btn-lg"%>			
			<%= link_to "Settings", physician_settings_path, :class => "btn btn-default btn-lg"%>
		</div>
   </div>
</nav>
<%= yield %>

</body>
</html>