cor-dashboard/config/routes.rb
CorDashboard::Application.routes.draw do
  
  get "patient/", to: "patient#alerts"
  get "patient/metrics"
  get "patient/alerts"
  get "patient/patient_plan"
  get "patient/activity_log"
  get "patient/settings"
  
  get "patient/weight"
  get "patient/blood_oxygen"
  get "patient/heart_rate"
  get "patient/heart_rate_trend"
  get "patient/sodium"
  get "patient/blood_pressure"
  get "patient/medication"
  get "patient/cough"

  get "patient/exercise_log"
  get "patient/sleep_log"
  get "patient/health_summary"
  get "patient/blood_pressure_trend"

  get 'physician/roster'
  get 'physician/critical_patients'
  get 'physician/alerts'
  get 'physician/patients'
  get 'physician/settings'
  get 'physician/summary'
  get 'physician/detail'

  root 'patient#metrics'

  

  

end

cor-dashboard/app/models/patient.rb
class Patient < ActiveRecord::Base

    attr_accessible :id, :physician_id, :name, :phone_number
    
		belongs_to :physician

    has_many :blood_oxygen_readings
    has_many :heart_rate_readings
    has_many :weight_readings
    has_many :blood_pressure_readings   
    has_many :emas
    has_many :alerts
    has_many :activities
    has_one :threshold_values

    if Rails.env.production?
      self.table_name = "patient_info"
      alias_attribute :name, :patient_name
      alias_attribute :id, :patient_id
    end

    def health_summary      
      # # Basic premise: Average the readings for last two weeks // Read most recent reading
      # # Compare to an ideal "green" value if possible. 
      # # Value to send to summary graph is mapped from its range to appropriate graph range

      #Weight Summary 
      wt_thresh = eval(threshold_values.weight)
      wt_over_interval = weight_readings.last_n_days(wt_thresh[:time]).map {|r| r.weight}
      wt_change = wt_over_interval.max - wt_over_interval.min
      if wt_change >= wt_thresh[:weight] # I'm hardcoding the max weight gain we expect
        wt_summ = map(wt_change, wt_thresh[:weight], 10, 5, 6 )
      else # I'm also hardcoding the max weight loss we expect
        wt_summ = map(wt_change, -10, wt_thresh[:weight], 2.5, 3.5)
      end    

      #Blood Oxygen Summary  

      bo_current = blood_oxygen_readings.latest.bo_perc
      if bo_current > threshold_values.bo_perc # Map good values to the 2.5-3 zone
        bo_summ = map(bo_current, threshold_values.bo_perc, 100.0, 2.5, 3)
      else # Map bad values to the 0-2 zone
        bo_summ = map(bo_current, 60.0, threshold_values.bo_perc, 0, 1.5)
      end  
      
      #Blood Pressure Summary

        # The value would be perfectly in the green zone if it was between the high and low thresholds
      green_sys = avg(eval(threshold_values.systolic_bp)[:high] , eval(threshold_values.systolic_bp)[:low]).to_f
      green_dia = avg(eval(threshold_values.diastolic_bp)[:high], eval(threshold_values.diastolic_bp)[:low]).to_f
     
      bp_sys_current = blood_pressure_readings.latest.systolic_bp.to_f
      bp_dia_current = blood_pressure_readings.latest.diastolic_bp.to_f
      
      bp_sys_change = change(bp_sys_current, green_sys)
      bp_dia_change = change(bp_dia_current, green_dia)

        # Whichever change is bigger (because we consider the "worst" bp value)      
      bp_change = max(bp_sys_change, bp_dia_change)

      bp_summ = map(bp_change, -1.0, 1.0, 0.5, 5.5)

      #Heart Rate Summary
      green_hr = avg(eval(threshold_values.heart_rate)[:high], eval(threshold_values.heart_rate)[:low])  
     
      hr_curr = heart_rate_readings.latest.heart_rate 
      hr_high = eval(threshold_values.heart_rate)[:high]
      hr_low = eval(threshold_values.heart_rate)[:low]
     
      if(hr_curr > hr_low && hr_curr < hr_high)
        hr_summ = map(hr_curr, hr_low, hr_high, 2.5, 3.5)
      elsif(hr_curr > hr_high)
        hr_summ = map(hr_curr, hr_high, 200, 4.5, 5.5)
      elsif (hr_curr < hr_low)
        hr_summ = map(hr_curr, 0, hr_low, 0, 1.5)
      end

      #Sodium Summary
     
      so_curr = sodiumStringToInt(emas.latest.sodium_level)
      
      so_summ = map(so_curr, 1,3, 3, 5) # Low is best, so it's in the green. Medium is on the border, High in the red
      
      # The map function converts a value from one range to another (see at foot of file)     
      return {weight: wt_summ, 
              heart_rate: hr_summ, 
              blood_oxygen: bo_summ,                       
              blood_pressure: bp_summ,              
              sodium: so_summ}
    end

    #Blood oxygen
    def blood_oxygen
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_week.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    def blood_oxygen_last_2_weeks
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    def blood_oxygen_last_month
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_month.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    def blood_oxygen_last_three_months
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_three_months.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    def blood_oxygen_last_six_months
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_six_months.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    def blood_oxygen_last_year
      return {threshold: threshold_values.bo_perc,
              values: blood_oxygen_readings.last_year.map {|r| [r.reading_time.utc.to_i*1000, r.bo_perc] }}
    end

    #Heart Rate
    def heart_rate    
      r = heart_rate_readings.latest
    	return {threshold: eval(threshold_values.heart_rate), 
      				values: [r.reading_time.utc.to_i*1000, r.heart_rate],
              variability: r.heart_rate_variability }  
    end

    def heart_rate_last_week
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_week.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end


    def heart_rate_last_2_weeks
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end

    def heart_rate_last_month
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_month.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end

    def heart_rate_last_three_months
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_three_months.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end

    def heart_rate_last_six_months
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_six_months.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end

    def heart_rate_last_year
      return {threshold: eval(threshold_values.heart_rate),
              values: heart_rate_readings.last_year.map {|r| [r.reading_time.utc.to_i*1000, r.heart_rate] }}
    end
    # Weight
    def weight
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    def weight_last_week
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_week.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    def weight_last_month
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_month.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    def weight_last_three_months
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_three_months.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    def weight_last_six_months
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_six_months.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    def weight_last_year
      return {threshold: eval(threshold_values.weight),
              values: weight_readings.last_year.map {|r| [r.reading_time.utc.to_i*1000, r.weight] }}

    end

    # Sodium

    def sodium
        return {threshold: 0,
                values: emas.last_week.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    def sodium_last_2_weeks
      return {threshold: 0,
              values: emas.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    def sodium_last_month
      return {threshold: 0,
              values: emas.last_month.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    def sodium_last_three_months
      return {threshold: 0,
              values: emas.last_three_months.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    def sodium_last_six_months
      return {threshold: 0,
              values: emas.last_six_months.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    def sodium_last_year
      return {threshold: 0,
              values: emas.last_year.map {|r| [r.reading_time.utc.to_i*1000, sodiumStringToInt(r.sodium_level)] }}
    end

    # Blood Pressure
    def blood_pressure
        r = blood_pressure_readings.latest
        return {threshold: {:systolic => eval(threshold_values.systolic_bp),
                            :diastolic => eval(threshold_values.diastolic_bp)} ,
        values: [r.reading_time.utc.to_i*1000, r.systolic_bp, r.diastolic_bp] }
    end

    def blood_pressure_last_week
      return {threshold: {systolic: eval(threshold_values.systolic_bp),
                          diastolic: eval(threshold_values.diastolic_bp)} ,
              values: {systolic: blood_pressure_readings.last_week.map {|r| [r.reading_time.utc.to_i*1000, r.systolic_bp] },
                        diastolic: blood_pressure_readings.last_week.map {|r| [r.reading_time.utc.to_i*1000, r.diastolic_bp] }} }
    end

    def blood_pressure_last_2_weeks
      return {threshold: {systolic: eval(threshold_values.systolic_bp),
                          diastolic: eval(threshold_values.diastolic_bp)} ,
              values: {systolic: blood_pressure_readings.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, r.systolic_bp] },
                       diastolic: blood_pressure_readings.last_2_weeks.map {|r| [r.reading_time.utc.to_i*1000, r.diastolic_bp] }} }
    end

    def blood_pressure_last_month

cor-dashboard/app/controllers/patient_controller.rb
class PatientController < ApplicationController

  respond_to :html, :js
  
  def metrics
    #Fetch summary data by patient_id  
    #@patient = Patient.find(params[:id]) 
    @patient = Patient.take
    #Have to get this data here too, since we start with health summary
    @values = @patient.health_summary
  end

  def health_summary
    patient = Patient.take
    @values = patient.health_summary
  end


  def blood_oxygen
    patient = Patient.take  
    bundle = patient.blood_oxygen
    @threshold = bundle[:threshold]
    @values = bundle[:values]
  end

  def heart_rate   
    patient = Patient.take        
    bundle = patient.heart_rate
    @threshold = bundle[:threshold]
    @values = bundle[:values]
    @variability = bundle[:variability]
  end

  def weight
    patient = Patient.take      
    bundle = patient.weight
    @threshold = bundle[:threshold]
    @values = bundle[:values]
  end

  def sodium
    patient = Patient.take 
    bundle = patient.sodium
    @threshold = bundle[:threshold]
    @values = bundle[:values]
  end

  def blood_pressure
    patient = Patient.take         
    bundle = patient.blood_pressure
    @threshold = bundle[:threshold]
    @values = bundle[:values]
  end

  def medication    
  end

  def cough
  end

  def alerts
    #Fetch alert data by patient_id
    @patient = Patient.take
    @alerts = @patient.scanForAlerts
    #redirect to alerts
  end

  def patient_plan
    #Fetch patient_plan data by patient_id    
    #redirect to patient_plan
  end

  def activity_log
    #Fetch activity_log data by patient_id     
    #redirect to activity_log
    @patient = Patient.take
    @exercise_log = @patient.activity_log[:exercise]
  end

  def exercise_log
    @patient = Patient.take
    @exercise_log = @patient.activity_log[:exercise]
  end

  def settings
    #Fetch settings data by patient_id    
    #redirect to settings
    @patient = Patient.take
  end
end

cor-dashboard/app/helpers/patient_helper.rb
module PatientHelper
end

cor-dashboard/app/views/patient/_blood_pressure.html.erb
<%= javascript_tag do %>
	var systolicHigh = <%= threshold[:systolic][:high] %>;
	var systolicLow = <%= threshold[:systolic][:low] %>;		
	var diastolicHigh = <%= threshold[:diastolic][:high] %>;
	var diastolicLow = <%= threshold[:diastolic][:low] %>;
	
	var timestamp = <%= values[0] %>;
	var systolicReading = <%= values[1] %>;
	var diastolicReading = <%= values[2] %>;
<% end %>

<div id="blood_pressure_container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
  $(populate_blood_pressure_container());
</script>
<% javascript_include_tag "blood_pressure"%>

cor-dashboard/app/views/patient/_blood_pressure_trend.html.erb
<%= javascript_tag do %>
    var systolicHigh = <%= threshold[:systolic][:high] %>;
    var systolicLow = <%= threshold[:systolic][:low] %>;
    var diastolicHigh = <%= threshold[:diastolic][:high] %>;
    var diastolicLow = <%= threshold[:diastolic][:low] %>;

    var systolicReading = <%= values[:systolic] %>;
    var diastolicReading = <%= values[:diastolic] %>;
    systolicReading.sort();
    diastolicReading.sort();
<% end %>

<div id="blood_pressure_trend_container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
    $(populate_blood_pressure_trend_container());
</script>
<% javascript_include_tag "blood_pressure_trend"%>

cor-dashboard/app/views/patient/_heart_rate.html.erb
<%= javascript_tag do %>
    var heartrateHigh = <%= threshold[:high] %>;
    var heartrateLow = <%= threshold[:low] %>;
    var variability = <%= variability %>;
    var timestamp = <%= values[0] %>;
    var heartrateReading = <%= values[1] %>;
<% end %>

<div id="heart_rate_container"></div>
<script>
    $(populate_heart_rate_container());
</script>
<% javascript_include_tag "heart_rate"%>

cor-dashboard/app/views/patient/_patient.html.erb
<a href="/physician/summary?id=<%=patient.id%>">
<div>
	<img src="http://placehold.it/200x200"></img>
	<h4 align="center"><%=patient.name%></h4>
</div>
</a>

cor-dashboard/app/views/patient/_sodium.html.erb
<%= javascript_tag do %>	
	var data = <%= values %>;	
	var threshold = <%= threshold %>;		
	data.sort();
<% end %>

<div id="sodium_container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>
<script>
  $(populate_sodium_container());
</script>
<% javascript_include_tag "sodium"%>

cor-dashboard/app/views/patient/_weight.html.erb
<%= javascript_tag do %>
  var data = <%= values %>;
  var weightThreshold = <%= threshold[:weight] %>;
  var timeThreshold = <%= threshold[:time] %>;

  data.sort();
<% end %>

<div id="weight_container"></div>
<script>
  $(populate_weight_container());
</script>
<% javascript_include_tag "weight"%>

cor-dashboard/app/views/patient/activity_log.html.erb
<div class="col-sm-2 col-sm-offset-1">
	<div id="metric-nav">
		<ul>		
			<li class="text-center btn-default border-r btn-spacing"><%= button_to "Exercise Log", patient_exercise_log_path, :remote => true, class:"btn btn-default w75", method: "get" %>
			</li>		
			<li class="text-center btn-default border-r btn-spacing"><%= button_to "Sleep Log", patient_sleep_log_path, :remote => true, class:"btn btn-default w75", method: "get" %>
			</li>    
		</ul>
	</div>	
</div>
<div id="metric-nav" class="col-md-8">
  <h2>Today's Steps: <%= @exercise_log[:steps].last %></h2>
	<div id="graph">
		
	</div>	
</div>
<script>
	$("a").removeClass("active");
	$("#myactivitylog a").css("padding-bottom","51px");
	$("#myactivitylog a").css("box-shadow","none");
	$("#myactivitylog a").css("border-radius","3px 3px 0 0");
</script>

<script>
$('#graph').html("<%= escape_javascript(render :partial => 'patient/exercise_log', :locals => {:exercise_log => @exercise_log})%>");
</script>

cor-dashboard/app/views/patient/alerts.html.erb
<div id="alertsdiv" class="col-sm-12">
	<h2 class="col-sm-offset-1" style="font-weight: lighter">Alerts and Notifications</h2>
	<ul>
		<% @alerts.each do |a| %>
			<li> 			
				<%= render :partial => 'patient/alert', :locals => {alert: a} %>		
			</li>
		<% end %>
	</ul>
	<script>
	// When we click on the a
	$("a").removeClass("active");
	$("#myalerts a").css("padding-bottom","51px");
	$("#myalerts a").css("box-shadow","none");
	$("#myalerts a").css("border-radius","3px 3px 0 0");
	// $("nav a")(function(){
	//   // If this isn't already active
	//   // if (!$(this).hasClass("active")) {
	//   // 	$(this).addClass("active");
	//     // Remove the class from anything that is active
	//     $("a").removeClass("active");
	//   //   // And make this active
	//     $("#myalerts").addClass("active");
	// });
	</script>
</div>

cor-dashboard/app/views/patient/heart_rate.js.erb
$('#graph').html("<%= escape_javascript(render :partial => 'patient/heart_rate', :locals => {:threshold => @threshold, :values => @values, :variability => @variability})%>");

cor-dashboard/app/views/patient/heart_rate_trend.js.erb
$('#graph').html("<%= escape_javascript(render :partial => 'patient/heart_rate_trend', :locals => {:threshold => @threshold, :values => @values})%>");

cor-dashboard/app/views/patient/metrics.html.erb
<div class="col-sm-2 col-sm-offset-1">
	<div id="metric-nav">
	<ul>
		<li class="text-center btn-default border-r btn-spacing"><%= button_to "Summary", patient_health_summary_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>
		<li class="text-center btn-default border-r btn-spacing"><%= button_to "Weight", patient_weight_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>		
		<li class="text-center btn-default border-r btn-spacing"><%= button_to "Blood Pressure", patient_blood_pressure_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>
    <li class="text-center btn-default border-r btn-spacing"><%= link_to "Heart Rate", patient_heart_rate_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>
		<li class="text-center btn-default border-r btn-spacing"><%= link_to "Blood Oxygen", patient_blood_oxygen_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>
		<li class="text-center btn-default border-r btn-spacing"><%= link_to "Sodium", patient_sodium_path, :remote => true, class:"btn btn-default w75", method: "get" %></li>
		</ul>
	</div>	
</div>
<div id="metric-nav" class="col-md-8">
	<div id="graph">
		<img src="http://placehold.it/900x400">
	</div>
</div>


<script>
   $('#graph').html("<%= escape_javascript(render :partial => 'patient/health_summary', :locals => {:values => @values})%>");
</script>

cor-dashboard/app/views/patient/patient_plan.html.erb
<h1>Patient#patient_plan</h1>
<p>Find me in app/views/patient/patient_plan.html.erb</p>
<script>
	$("a").removeClass("active");
	$("#mypatientplan a").css("padding-bottom","51px");
	$("#mypatientplan a").css("box-shadow","none");
	$("#mypatientplan a").css("border-radius","3px 3px 0 0");
</script>

cor-dashboard/app/views/patient/sodium.js.erb
$('#graph').html("<%= escape_javascript(render :partial => 'patient/sodium', :locals => {:threshold => @threshold, :values => @values})%>");

cor-dashboard/app/views/patient/weight.js.erb
$('#graph').html("<%= escape_javascript(render :partial => 'patient/weight', :locals => {:threshold => @threshold, :values => @values})%>");