cor-dashboard/config/routes.rb
CorDashboard::Application.routes.draw do
  
  get "patient/", to: "patient#alerts"
  get "patient/metrics"
  get "patient/alerts"
  get "patient/patient_plan"
  get "patient/activity_log"
  get "patient/settings"
  
  get "patient/weight"
  get "patient/blood_oxygen"
  get "patient/heart_rate"
  get "patient/heart_rate_trend"
  get "patient/sodium"
  get "patient/blood_pressure"
  get "patient/medication"
  get "patient/cough"

  get "patient/exercise_log"
  get "patient/sleep_log"
  get "patient/health_summary"
  get "patient/blood_pressure_trend"

  get 'physician/roster'
  get 'physician/critical_patients'
  get 'physician/alerts'
  get 'physician/patients'
  get 'physician/settings'
  get 'physician/summary'
  get 'physician/detail'

  root 'patient#metrics'

  

  

end

cor-dashboard/app/models/physician.rb
class Physician < ActiveRecord::Base
    attr_accessible :name
    has_many :patients

    if Rails.env.production?
      self.table_name = "physician"
    end
end

cor-dashboard/app/controllers/physician_controller.rb
class PhysicianController < ApplicationController

	respond_to :html, :js

	def roster	
		@physician = Physician.take
		@patients = @physician.patients
        @borders = {}
        @patients.each do |patient|            
            if patient.alerts.exists?({resolved_physician: false, urgent: true})           
                @borders[patient.id] = 'critical'
            elsif patient.alerts.exists?({resolved_physician: false, urgent: false})
                 @borders[patient.id] = 'warning'               
            end
        end
	end 

	def critical_patients
		
	end

	def alerts
    @alerts = {}
    @physician = Physician.take
    @patients = @physician.patients
    @patients.each do |patient|
      @alerts[patient.id] = patient.scanForAlerts
    end
	end

	def patients
		
	end

	def settings
		
	end

	def summary
		@physician = Physician.take
		@patient = Patient.find(params[:id])
		@bundle = {}
		@bundle[:blood_oxygen] = @patient.blood_oxygen
    @bundle[:heart_rate] = @patient.heart_rate
		@bundle[:weight] = @patient.weight
		@bundle[:sodium] = @patient.sodium
		@bundle[:blood_pressure] = @patient.blood_pressure
    @exercise_log = @patient.activity_log[:exercise]

    @borders = {}
    if @patient.alerts.exists?({resolved_physician: false, urgent: true, metric_name: "blood oxygen"})
      @borders[:blood_oxygen] = 'critical'
    elsif @patient.alerts.exists?({resolved_physician: false, urgent: false, metric_name: "blood oxygen"})
      @borders[:blood_oxygen] = 'warning'
    end

    if @patient.alerts.exists?({resolved_physician: false, urgent: true, metric_name: "blood pressure"})
      @borders[:blood_pressure] = 'critical'
    elsif @patient.alerts.exists?({resolved_physician: false, urgent: false, metric_name: "blood pressure"})
      @borders[:blood_pressure] = 'warning'
    end

    if @patient.alerts.exists?({resolved_physician: false, urgent: true, metric_name: "heart rate"})
      @borders[:heart_rate] = 'critical'
    elsif @patient.alerts.exists?({resolved_physician: false, urgent: false, metric_name: "heart rate"})
      @borders[:heart_rate] = 'warning'
    end

    if @patient.alerts.exists?({resolved_physician: false, urgent: true, metric_name: "weight"})
      @borders[:weight] = 'critical'
    elsif @patient.alerts.exists?({resolved_physician: false, urgent: false, metric_name: "weight"})
      @borders[:weight] = 'warning'
    end

    if @patient.alerts.exists?({resolved_physician: false, urgent: true, metric_name: "sodium"})
      @borders[:sodium] = 'critical'
    elsif @patient.alerts.exists?({resolved_physician: false, urgent: false, metric_name: "sodium"})
      @borders[:sodium] = 'warning'
    end
	end

	def detail
        @values = {}
        @metric = params[:metric]
        @physician = Physician.take
        #@patients = @physician.patients
        @patient = Patient.find(params[:patientId])
        # last_week
        bundle = @patient.weight_last_week
        @threshold_wt = bundle[:threshold]
        @values_wt = bundle[:values]
        bundle = @patient.blood_oxygen
        @threshold_bo = bundle[:threshold]
        @values_bo = bundle[:values]
        bundle = @patient.heart_rate_last_week
        @threshold_hr = bundle[:threshold]
        @values_hr = bundle[:values]
        bundle = @patient.blood_pressure_last_week
        @threshold_bp = bundle[:threshold]
        @values_bp = bundle[:values]
        bundle = @patient.sodium
        @threshold_so = bundle[:threshold]
        @values_so = bundle[:values]
        @exercise_log = @patient.activity_log[:exercise]

        # last_2_weeks
        bundle = @patient.weight
        @threshold_wt2w = bundle[:threshold]
        @values_wt2w = bundle[:values]
        bundle = @patient.blood_oxygen_last_2_weeks
        @threshold_bo2w = bundle[:threshold]
        @values_bo2w = bundle[:values]
        bundle = @patient.heart_rate_last_2_weeks
        @threshold_hr2w = bundle[:threshold]
        @values_hr2w = bundle[:values]
        bundle = @patient.blood_pressure_last_2_weeks
        @threshold_bp2w = bundle[:threshold]
        @values_bp2w = bundle[:values]
        bundle = @patient.sodium_last_2_weeks
        @threshold_so2w = bundle[:threshold]
        @values_so2w = bundle[:values]
        @exercise_log_2w = @patient.activity_log_last_2_weeks[:exercise]

        # last_month
        bundle = @patient.weight_last_month
        @threshold_wtm = bundle[:threshold]
        @values_wtm = bundle[:values]
        bundle = @patient.blood_oxygen_last_month
        @threshold_bom = bundle[:threshold]
        @values_bom = bundle[:values]
        bundle = @patient.heart_rate_last_month
        @threshold_hrm = bundle[:threshold]
        @values_hrm = bundle[:values]
        bundle = @patient.blood_pressure_last_month
        @threshold_bpm = bundle[:threshold]
        @values_bpm = bundle[:values]
        bundle = @patient.sodium_last_month
        @threshold_som = bundle[:threshold]
        @values_som = bundle[:values]
        @exercise_log_m = @patient.activity_log_last_month[:exercise]

        # last_three_months
        bundle = @patient.weight_last_three_months
        @threshold_wt3m = bundle[:threshold]
        @values_wt3m = bundle[:values]
        bundle = @patient.blood_oxygen_last_three_months
        @threshold_bo3m = bundle[:threshold]
        @values_bo3m = bundle[:values]
        bundle = @patient.heart_rate_last_three_months
        @threshold_hr3m = bundle[:threshold]
        @values_hr3m = bundle[:values]
        bundle = @patient.blood_pressure_last_three_months
        @threshold_bp3m = bundle[:threshold]
        @values_bp3m = bundle[:values]
        bundle = @patient.sodium_last_three_months
        @threshold_so3m = bundle[:threshold]
        @values_so3m = bundle[:values]

        # last_six_months
        bundle = @patient.weight_last_six_months
        @threshold_wt6m = bundle[:threshold]
        @values_wt6m = bundle[:values]
        bundle = @patient.blood_oxygen_last_six_months
        @threshold_bo6m = bundle[:threshold]
        @values_bo6m = bundle[:values]
        bundle = @patient.heart_rate_last_six_months
        @threshold_hr6m = bundle[:threshold]
        @values_hr6m = bundle[:values]
        bundle = @patient.blood_pressure_last_six_months
        @threshold_bp6m = bundle[:threshold]
        @values_bp6m = bundle[:values]
        bundle = @patient.sodium_last_six_months
        @threshold_so6m = bundle[:threshold]
        @values_so6m = bundle[:values]

        # last_year
        bundle = @patient.weight_last_year
        @threshold_wty = bundle[:threshold]
        @values_wty = bundle[:values]
        bundle = @patient.blood_oxygen_last_year
        @threshold_boy = bundle[:threshold]
        @values_boy = bundle[:values]
        bundle = @patient.heart_rate_last_year
        @threshold_hry = bundle[:threshold]
        @values_hry = bundle[:values]
        bundle = @patient.blood_pressure_last_year
        @threshold_bpy = bundle[:threshold]
        @values_bpy = bundle[:values]
        bundle = @patient.sodium_last_year
        @threshold_soy = bundle[:threshold]
        @values_soy = bundle[:values]

    end
end

cor-dashboard/app/views/physician/_table.erb
<% if metric == "weight"%>
<table class="table" id="weight_tab">
  <thead>
  <tr>
    <th>Reading Time</th>
    <th>Weight</th>
  </tr>
  </thead>
  <tbody>
  <% values_weight.each do |i| %>
      <tr>
        <% sec = (i[0].to_f / 1000) %>
        <% datetime = Time.at(sec) %>
        <th><%=datetime%></th>
        <th><%= i[1] %></th>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<% if metric == "blood_pressure_trend" %>
<table class="table" id="bloodpressure_tab">
  <thead>
  <tr>
    <th>Reading Time</th>
    <th>Systolic</th>
    <th>Diastolic</th>
  </tr>
  </thead>
  <tbody>
  <% for i in 0..values_blood_pressure[:systolic].length - 1 %>
      <tr>
        <% sec = (values_blood_pressure[:systolic][i][0].to_f / 1000) %>
        <% datetime = Time.at(sec) %>
        <th><%=datetime%></th>
        <th><%= values_blood_pressure[:systolic][i][1] %></th>
        <th><%= values_blood_pressure[:diastolic][i][1] %></th>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<% if metric == "heart_rate_trend" %>
<table class="table" id="heartrate_tab">
  <thead>
  <tr>
    <th>Reading Time</th>
    <th>Heart Rate</th>
  </tr>
  </thead>
  <tbody>
  <% values_heart_rate.each do |i| %>
      <tr>
        <% sec = (i[0].to_f / 1000) %>
        <% datetime = Time.at(sec) %>
        <th><%=datetime%></th>
        <th><%= i[1] %></th>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<% if metric == "blood_oxygen" %>
<table class="table" id="bloodoxygen_tab">
  <thead>
  <tr>
    <th>Reading Time</th>
    <th>Blood Oxygen %</th>
  </tr>
  </thead>
  <tbody>
  <% values_blood_oxygen.each do |i| %>
      <tr>
        <% sec = (i[0].to_f / 1000) %>
        <% datetime = Time.at(sec) %>
        <th><%=datetime%></th>
        <th><%= i[1] %></th>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<% if metric == "activity" %>
<table class="table" id="activity_tab">
  <thead>
  <tr>
    <th>Day</th>
    <th>Sedentary minutes</th>
    <th>Lightly active minutes</th>
    <th>Fairly active minutes</th>
    <th>Very active minutes</th>
    <th>Steps</th>
  </tr>
  </thead>
  <tbody>
  <% for i in 0..(values_activity[:days].length - 1) %>
    <tr>
      <th><%= values_activity[:days][i] %></th>
      <th><%= values_activity[:sedentary][i] %></th>
      <th><%= values_activity[:lightly_active][i] %></th>
      <th><%= values_activity[:fairly_active][i] %></th>
      <th><%= values_activity[:very_active][i] %></th>
      <th><%= values_activity[:steps][i] %></th>
    </tr>
  <% end %>
  </tbody>
</table>
<% end %>

<% if metric == "sodium" %>
<table class="table" id="sodium_tab">
  <thead>
  <tr>
    <th>Reading Time</th>
    <th>Sodium</th>
  </tr>
  </thead>
  <tbody>
  <% values_sodium.each do |i| %>
      <tr>
        <% sec = (i[0].to_f / 1000) %>
        <% datetime = Time.at(sec) %>
        <th><%=datetime%></th>
        <% if i[1] == 1 %>
            <th>Low</th>
        <% end %>
        <% if i[1] == 2 %>
            <th>Medium</th>
        <% end %>
        <% if i[1] == 3 %>
            <th>High</th>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<% end %>

cor-dashboard/app/views/physician/alerts.html.erb
<div id="alertsdiv" class="col-sm-12">
	<h2 class="col-sm-offset-1" style="font-weight: lighter">Alerts and Notifications</h2>
	<ul>
		<% @alerts.each do |patientAlerts| %>
            <p> Alerts for <%= Patient.find(patientAlerts[0]).name %></p>
            <% patientAlerts[1].each do |a| %>
			    <li>
				    <%= render :partial => 'patient/alert', :locals => {alert: a} %>
			    </li>
		    <% end %>
        <% end %>
	</ul>
</div>

cor-dashboard/app/views/physician/roster.html.erb
<div class="col-lg-12" id="patient-container">
  <div style="padding-left: 50px;">
	<% @patients.in_groups_of(5) do |group| %>
		<div class="row" style="padding-left: 20px;">
			<% group.each do |patient| %>	
				<% if patient != nil %>										
					<div class="col-md-2 patientroster-container" id="<%= @borders[patient.id] %>" >						
						<%= render :partial => 'patient/patient', :locals => {:patient => patient} %>
					</div>
				<% end %>
			<% end %>
		</div>
	<% end %>
	</div>
</div>

cor-dashboard/app/views/physician/summary.html.erb
<div class="col col-lg-2" style="max-width: 20%;">
  <div class="row" style="padding-left: 10px;">
    <ul>
      <li>
          <div class="col col-md-1" id="patientpic-container">
            <img src="http://placehold.it/200x220"></img>
            <h4 align="center"><%=@patient.name%></h4>
            <h4 align="center"><%=@patient.phone_number%></h4>
          </div>
      </li>
      <li> <div class="col col-md-1" id="patientinfo-container"></div>  </li>
      <li><div class="col col-md-2" id="medication-container"></div>   </li>
    </ul>
  </div>
</div>
<div class="col col-md-10">
   <div class="row">
	<div class="col-md-6 summarygraph-container" id="<%= @borders[:weight] %>">
		<%= link_to physician_detail_path(:metric => "weight", :patientId => @patient.id) do %>
			<div id="weight_graph">Weight</div>
		<% end %>
    </div>
    <div class="col-md-6 summarygraph-container" id="<%= @borders[:heart_rate] %>">
		<%= link_to physician_detail_path(:metric => "heart_rate_trend", :patientId => @patient.id) do %>
			<div id="hr_graph">Heart Rate</div>
		<% end %>
    </div>
    </div> <br>
     <div class="row">
     <div class="col-md-6 summarygraph-container" id="<%= @borders[:blood_oxygen] %>">
		<%= link_to physician_detail_path(:metric => "blood_oxygen", :patientId => @patient.id) do %>
			<div id="bo_graph">Blood Oxygen</div>
		<% end %>
     </div>
     <div class="col-md-6 summarygraph-container" id="<%= @borders[:blood_pressure] %>">
		<%= link_to physician_detail_path(:metric => "blood_pressure", :patientId => @patient.id) do %>
			<div id="bp_graph">Blood Pressure</div>
		<% end %>
	</div>
       </div> <br>
  <div class="row">
	<div class="col-md-6 summarygraph-container">
		<%= link_to physician_detail_path(:metric => "activity", :patientId => @patient.id) do %>
			<div id="activity_graph">Activity</div>
		<% end %>
      </div>
     <!--div class="col-md-6" id="summarygraph-container">
		<%= link_to physician_detail_path(:metric => "medication", :patientId => @patient.id) do %>
			<div id="medication_graph">Medication</div>
		<% end %>
       </div>
    </div> <br>
  <div class="row"-->
     <div class="col-md-6 summarygraph-container" id="<%= @borders[:sodium] %>">
		<%= link_to physician_detail_path(:metric => "sodium", :patientId => @patient.id) do %>
			<div id="sodium_graph">Sodium</div>
		<% end %>
	</div>
    </div>
</div>

<script>
	$('#bo_graph').html("<%= escape_javascript(render :partial => 'patient/blood_oxygen', :locals => @bundle[:blood_oxygen])%>");
	$('#hr_graph').html("<%= escape_javascript(render :partial => 'patient/heart_rate', :locals => @bundle[:heart_rate])%>");
	$('#weight_graph').html("<%= escape_javascript(render :partial => 'patient/weight', :locals => @bundle[:weight])%>");
	$('#sodium_graph').html("<%= escape_javascript(render :partial => 'patient/sodium', :locals => @bundle[:sodium])%>");
	$('#bp_graph').html("<%= escape_javascript(render :partial => 'patient/blood_pressure', :locals => @bundle[:blood_pressure])%>");
    $('#activity_graph').html("<%= escape_javascript(render :partial => 'patient/exercise_log', :locals => {:exercise_log => @exercise_log})%>");

</script>